### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by tanshao111** [BNN-UPC/TwinNet#1]
![问题1](https://github.com/BNN-UPC/TwinNet/assets/155713705/0da6bd6c-3653-4ee5-887d-739b3f614623)
![问题2](https://github.com/BNN-UPC/TwinNet/assets/155713705/e3c36e1c-f8e5-4a43-89f0-f66fa0234f64)
Hello, when I was running the main.py script in the folder, I encountered the following issue. I am not sure whether it is related to the dataset or something else. Could you please help me with this?

**Comment by MiquelFerriol** [comment]
Dear @tanshao111,
Thank you for reaching us out. To be honest, it is the first time I encounter this error.

To help you regarding this issue could you please provide the Tensorflow Version you are using and the OS? (It looks that in Windows, if the absolute path is larger than 260 characters, the OS restricts it. If that's the case, you need to enable the LongPathsEnabled register).

Best regards,
Miquel

**Comment by tanshao111** [comment]
Dear Miquel,

Thank you very much for your swift and helpful response. Indeed, I am using Windows 11 as my operating system. The version of TensorFlow I have installed is 2.6.5. Upon checking, I've noticed that the absolute path does not seem to exceed 260 characters, so I believe the issue might be something else.

Could you please guide me on what other aspects I should look into or any additional information you might need from me to diagnose the problem?

I appreciate your assistance and looking forward to your guidance.

Best regards,

tanshao111
![tensorflow版本](https://github.com/BNN-UPC/TwinNet/assets/155713705/da688a2d-d8b0-4c7b-920e-b0716b163878)
![文件目录](https://github.com/BNN-UPC/TwinNet/assets/155713705/80492df6-21ed-4910-b531-1c8a8678ff7d)
![config](https://github.com/BNN-UPC/TwinNet/assets/155713705/c6125a07-2c31-4ae5-8256-1160daf161f6)

**Comment by MiquelFerriol** [comment]
The only thing I can think of now may be the TF version. TwinNet was built using TF2.0 and (maybe?) is causing some incompatibility issues.

It is kinda weird but, because the error raised is a TF error, not an implementation/incompatibility one.

What is even weirder is the fact that it also raises an UnicodeError, that may be related to the previous one...

I would try downgrading the Tensorflow version to see if the changed some specs about the estimator library, and let's see if it solves the problem.

**Comment by tanshao111** [comment]
Thank you very much for your help. I have switched to TensorFlow version 2.0.4 and the code is now running successfully.
